# Generated by Django 4.1.6 on 2023-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('isClient', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
